project_id = "bdfyrtobxkwxobjspxjo"

[functions.auth-security]
verify_jwt = false

[functions.captcha-verification]
verify_jwt = false

[functions.mfa-service]
verify_jwt = true

[functions.security-monitor]
verify_jwt = false